services:
    gcloud_storage_client:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            -   projectId: '%env(GCS_PROJECT_ID)%'
                keyFile:
                    type: '%env(GCS_TYPE)%'
                    project_id: '%env(GCS_PROJECT_ID)%'
                    private_key_id: '%env(GCS_PRIVATE_KEY_ID)%'
                    private_key: '%env(GCS_PRIVATE_KEY)%'
                    client_email: '%env(GCS_CLIENT_EMAIL)%'
                    client_id: '%env(GCS_CLIENT_ID)%'
                    auth_uri: '%env(GCS_AUTH_URI)%'
                    token_uri: '%env(GCS_TOKEN_URI)%'
                    auth_provider_x509_cert_url: '%env(GCS_AUTH_PROVIDER_X509_CERT_URL)%'
                    client_x509_cert_url: '%env(GCS_CLIENT_X509_CERT_URL)%'

flysystem:
    storages:
        image.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/data/images'

        gcloud_collectables.storage:
            adapter: 'gcloud'
            options:
                client: 'gcloud_storage_client'
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'collectables'

        gcloud_generated_images.storage:
            adapter: 'gcloud'
            options:
                client: 'gcloud_storage_client'
                bucket: '%env(GCS_BUCKET)%'
                prefix: 'collectables'