monolog:
    handlers:
        rollbar:
            type: service
            id: Rollbar\Monolog\Handler\RollbarHandler
        main:
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 10