# config/routes.yaml

# API Platform routes
api_platform:
    resource: .
    type: api_platform
    prefix: /api

# Other routes for your application
app_routes:
    resource: '../src/Controller/'
    type: annotation
