parameters:
    telegram_route_secret: '%env(TELEGRAM_BOT_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            string $telegramToken: '%env(TELEGRAM_BOT_TOKEN)%'
            string $extraSpicySpamChatId: '%env(EXTRA_SPICY_SPAM_CHAT_ID)%'
            string $openAiApiKey: '%env(OPENAI_API_KEY)%'
            string $finnhubApiKey: '%env(FINNHUB_API_KEY)%'
            string $frontendUrl: '%env(FRONTEND_URL)%'
            string $backendUrl: '%env(BACKEND_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    app.telegram_authenticator:
        class: App\Security\TelegramAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator

    App\OpenApi\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@App\OpenApi\OpenApiFactory.inner' ]
        autoconfigure: false

    App\ApiPlatform\Filter\UserFilter:
        arguments: ['@security.helper']
        tags: ['api_platform.filter']
        autoconfigure: false

    App\Doctrine\CurrentUserExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
            - { name: api_platform.doctrine.orm.query_extension.item }