parameters:
    telegram_route_secret: '%env(TELEGRAM_BOT_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            string $telegramToken: '%env(TELEGRAM_BOT_TOKEN)%'
            string $extraSpicySpamChatId: '%env(EXTRA_SPICY_SPAM_CHAT_ID)%'
            string $openAiApiKey: '%env(OPENAI_API_KEY)%'
            string $finnhubApiKey: '%env(FINNHUB_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'