name: 🚀 Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  APP_ENV: prod
  ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}

jobs:
  build:
    name: 🛠️ Build
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - uses: actions/checkout@v3

      - name: 🔐 Create .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local

      - name: 🔨 Setup php composer dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: 8.0.2
          version: 2.x

      - name: 🌐 FTP sync changes
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 185.117.169.140
          server-dir: ./subdomains/extra-spicy-spam/httpdocs/
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            var/**
            package.*
            .github/**
            readme.md

      - name: 🧹 Clean up FTP
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: 185.117.169.140
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: '*.log;docker_tag;DOCKER_ENV;Dockerfile-php-build'
          #remoteDirectories: 'var'
          workingDir: './subdomains/extra-spicy-spam/httpdocs/'
          ignoreSSL: 1